//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products_174772
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products_174772()
        {
            this.OrderDetails_174772 = new HashSet<OrderDetails_174772>();
            this.ShoppingCart_174772 = new HashSet<ShoppingCart_174772>();
        }
    
        public int ProductId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string ModelNumber { get; set; }
        public string ModelName { get; set; }
        public Nullable<int> UnitCost { get; set; }
        public string Description { get; set; }
    
        public virtual Categories_174772 Categories_174772 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetails_174772> OrderDetails_174772 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoppingCart_174772> ShoppingCart_174772 { get; set; }
    }
}
