//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberShop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MINIPROJECT_174772Entities : DbContext
    {
        public MINIPROJECT_174772Entities()
            : base("name=MINIPROJECT_174772Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categories_174772> Categories_174772 { get; set; }
        public virtual DbSet<Customers_174772> Customers_174772 { get; set; }
        public virtual DbSet<OrderDetails_174772> OrderDetails_174772 { get; set; }
        public virtual DbSet<Orders_174772> Orders_174772 { get; set; }
        public virtual DbSet<Products_174772> Products_174772 { get; set; }
        public virtual DbSet<ShoppingCart_174772> ShoppingCart_174772 { get; set; }
    
        public virtual ObjectResult<SearchProduct_Result> SearchProduct(string modelName)
        {
            var modelNameParameter = modelName != null ?
                new ObjectParameter("ModelName", modelName) :
                new ObjectParameter("ModelName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchProduct_Result>("SearchProduct", modelNameParameter);
        }
    }
}
